const colors = {
  light: {
    text: "#0f0a2e",
    tint: "#5b5fc7",
    background: "#f8f9ff",
    foreground: "#0f0a2e",
    card: "#ffffff",
    cardForeground: "#0f0a2e",
    primary: "#5b5fc7",
    primaryForeground: "#ffffff",
    secondary: "#eef0ff",
    secondaryForeground: "#3d3f7d",
    muted: "#eef0ff",
    mutedForeground: "#7c7ea8",
    accent: "#eef0ff",
    accentForeground: "#3d3f7d",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e4e6f5",
    input: "#e4e6f5",
  },
  dark: {
    text: "#e8e9ff",
    tint: "#818cf8",
    background: "#0d0d1a",
    foreground: "#e8e9ff",
    card: "#161628",
    cardForeground: "#e8e9ff",
    primary: "#818cf8",
    primaryForeground: "#0d0d1a",
    secondary: "#1e1e3a",
    secondaryForeground: "#c7c9f8",
    muted: "#1e1e3a",
    mutedForeground: "#7c7ea8",
    accent: "#1e1e3a",
    accentForeground: "#c7c9f8",
    destructive: "#f87171",
    destructiveForeground: "#0d0d1a",
    border: "#2a2a4a",
    input: "#2a2a4a",
  },
  radius: 12,
};

export default colors;
