import { Feather } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import React from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { useColors } from "@/hooks/useColors";

export default function TermsOfServiceScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const router = useRouter();

  const s = makeStyles(colors, insets);

  return (
    <View style={s.container}>
      <View style={s.header}>
        <Pressable
          style={({ pressed }) => [s.backButton, pressed && { opacity: 0.6 }]}
          onPress={() => router.back()}
        >
          <Feather name="arrow-left" size={20} color={colors.foreground} />
        </Pressable>
        <Text style={s.headerTitle}>Terms of Service</Text>
        <View style={s.backButton} />
      </View>

      <ScrollView
        contentContainerStyle={s.content}
        showsVerticalScrollIndicator={false}
      >
        <Text style={s.lastUpdated}>Last updated: May 2026</Text>

        <Text style={s.intro}>
          By using GoalGetter you agree to these Terms of Service. Please read them
          carefully before using the app.
        </Text>

        <Text style={s.heading}>1. Description of Service</Text>
        <Text style={s.body}>
          GoalGetter is a mobile application available on iOS and Android that uses
          artificial intelligence to generate step-by-step plans from user-submitted goals.
        </Text>

        <Text style={s.heading}>2. User Responsibilities</Text>
        <Text style={s.body}>
          You must be at least 13 years old to use GoalGetter. You are responsible for
          keeping your account credentials secure and for all activity under your account.
          You may not use the service to generate content that is harmful, misleading,
          illegal, or violates any applicable law.
        </Text>

        <Text style={s.heading}>3. Free and Pro Plans</Text>
        <Text style={s.body}>
          GoalGetter offers a free tier with limited plan generations per month. The Pro
          subscription unlocks unlimited plan generations, custom app themes, custom app
          icons, and access to future Pro-only features. Feature availability may change
          with reasonable notice.
        </Text>

        <Text style={s.heading}>4. Subscription Terms</Text>
        <Text style={s.body}>
          Pro is billed monthly or annually via in-app purchase through the Apple App Store
          or Google Play Store. Subscriptions renew automatically unless cancelled at least
          24 hours before the renewal date. The subscription price is displayed at checkout
          and may be updated with 30 days&apos; prior notice. No charge is incurred during a
          free trial period if one is offered.
        </Text>

        <Text style={s.heading}>5. Cancellation and Refunds</Text>
        <Text style={s.body}>
          You may cancel your subscription at any time through your device&apos;s App Store
          or Google Play subscription settings. Cancellation takes effect at the end of
          the current billing period — you retain Pro access until then. Refunds are
          subject to the Apple App Store or Google Play refund policies. GoalGetter does
          not issue refunds directly.
        </Text>

        <Text style={s.heading}>6. Pro Feature Entitlements</Text>
        <Text style={s.body}>
          Pro features (custom themes, app icons, and others) are available only during an
          active Pro subscription. When a subscription expires or is cancelled, Pro features
          revert to free-tier defaults. Your goals and plans are never deleted due to a
          subscription change.
        </Text>

        <Text style={s.heading}>7. AI-Generated Content</Text>
        <Text style={s.body}>
          Plans generated by GoalGetter are produced by AI and may not always be accurate,
          complete, or suitable for your specific situation. GoalGetter makes no warranty
          about the quality or accuracy of AI-generated content. Do not substitute
          AI-generated plans for professional, medical, legal, or financial advice.
        </Text>

        <Text style={s.heading}>8. Termination</Text>
        <Text style={s.body}>
          You may delete your account at any time from the Profile screen. We reserve the
          right to suspend or terminate accounts that violate these terms, with or without
          notice.
        </Text>

        <Text style={s.heading}>9. Limitation of Liability</Text>
        <Text style={s.body}>
          GoalGetter is provided &quot;as is&quot; without warranty of any kind, express or
          implied. To the maximum extent permitted by applicable law, GoalGetter and its
          creators are not liable for any direct, indirect, incidental, or consequential
          damages arising from your use of the service.
        </Text>

        <Text style={s.heading}>10. Governing Law</Text>
        <Text style={s.body}>
          These terms are governed by the laws of the United States, without regard to
          conflict of law principles.
        </Text>

        <Text style={s.heading}>11. Contact</Text>
        <Text style={s.body}>
          Questions about these terms? Contact us at: legal@goalgetter.app
        </Text>
      </ScrollView>
    </View>
  );
}

function makeStyles(
  colors: ReturnType<typeof useColors>,
  insets: ReturnType<typeof useSafeAreaInsets>,
) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingTop: insets.top + 8,
      paddingBottom: 12,
      backgroundColor: colors.background,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backButton: {
      width: 36,
      height: 36,
      alignItems: "center",
      justifyContent: "center",
    },
    headerTitle: {
      fontSize: 16,
      fontFamily: "Inter_600SemiBold",
      color: colors.foreground,
    },
    content: {
      paddingHorizontal: 24,
      paddingTop: 20,
      paddingBottom: insets.bottom + 48,
    },
    lastUpdated: {
      fontSize: 12,
      color: colors.mutedForeground,
      fontFamily: "Inter_400Regular",
      marginBottom: 16,
    },
    intro: {
      fontSize: 15,
      color: colors.foreground,
      fontFamily: "Inter_400Regular",
      lineHeight: 24,
      marginBottom: 24,
    },
    heading: {
      fontSize: 16,
      color: colors.foreground,
      fontFamily: "Inter_600SemiBold",
      marginTop: 24,
      marginBottom: 8,
    },
    body: {
      fontSize: 14,
      color: colors.foreground,
      fontFamily: "Inter_400Regular",
      lineHeight: 22,
      marginBottom: 4,
    },
  });
}
