import React from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { useColors } from "@/hooks/useColors";

export default function TermsOfServiceScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();

  const s = makeStyles(colors, insets);

  return (
    <View style={s.container}>
      <ScrollView
        contentContainerStyle={s.content}
        showsVerticalScrollIndicator={false}
      >
        <Text style={s.lastUpdated}>Last updated: May 2026</Text>

        <Text style={s.intro}>
          By using GoalGetter you agree to these Terms of Service. Please read them
          carefully.
        </Text>

        <Text style={s.heading}>Use of the Service</Text>
        <Text style={s.body}>
          GoalGetter is provided for personal, non-commercial use. You may not use the
          service to generate content that is harmful, misleading, or violates any
          applicable law.
        </Text>

        <Text style={s.heading}>Free and Pro Plans</Text>
        <Text style={s.body}>
          Guest users may generate up to 3 plans. Registered free users have access to
          additional features. Pro subscribers get unlimited plans and exclusive themes.
          Subscriptions are billed monthly or annually and renew automatically unless
          cancelled.
        </Text>

        <Text style={s.heading}>AI-Generated Content</Text>
        <Text style={s.body}>
          Plans are generated by AI and may not always be accurate, complete, or suitable
          for your specific situation. GoalGetter makes no warranty about the quality or
          accuracy of AI-generated plans.
        </Text>

        <Text style={s.heading}>Account Termination</Text>
        <Text style={s.body}>
          You may delete your account at any time from the Profile screen. We reserve the
          right to terminate accounts that violate these terms.
        </Text>

        <Text style={s.heading}>Limitation of Liability</Text>
        <Text style={s.body}>
          GoalGetter is provided &quot;as is&quot; without warranty of any kind. We are not
          liable for any damages arising from your use of the service.
        </Text>

        <Text style={s.heading}>Contact</Text>
        <Text style={s.body}>
          Questions about these terms? Contact us at legal@goalgetter.app.
        </Text>
      </ScrollView>
    </View>
  );
}

function makeStyles(
  colors: ReturnType<typeof useColors>,
  insets: ReturnType<typeof useSafeAreaInsets>,
) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    content: {
      paddingHorizontal: 24,
      paddingTop: 20,
      paddingBottom: insets.bottom + 40,
    },
    lastUpdated: {
      fontSize: 12,
      color: colors.mutedForeground,
      fontFamily: "Inter_400Regular",
      marginBottom: 16,
    },
    intro: {
      fontSize: 15,
      color: colors.foreground,
      fontFamily: "Inter_400Regular",
      lineHeight: 24,
      marginBottom: 24,
    },
    heading: {
      fontSize: 16,
      fontWeight: "600" as const,
      color: colors.foreground,
      fontFamily: "Inter_600SemiBold",
      marginTop: 20,
      marginBottom: 8,
    },
    body: {
      fontSize: 14,
      color: colors.foreground,
      fontFamily: "Inter_400Regular",
      lineHeight: 22,
      marginBottom: 4,
    },
  });
}
