import React from "react";
import { Link } from "wouter";
import { Layout } from "@/components/layout";

export default function Terms() {
  return (
    <Layout>
      <article className="prose prose-slate dark:prose-invert prose-headings:font-serif prose-headings:font-normal prose-h1:text-5xl prose-h2:text-3xl prose-h2:mt-12 prose-a:text-primary hover:prose-a:text-primary/80 prose-a:no-underline max-w-none animate-in fade-in slide-in-from-bottom-4 duration-500">
        <header className="mb-16 not-prose text-center">
          <h1 className="text-5xl md:text-6xl mb-6 text-foreground">Terms of Service</h1>
          <p className="text-muted-foreground uppercase tracking-widest text-sm font-medium">Last updated: May 2026</p>
        </header>

        <h2>1. Introduction</h2>
        <p>
          By using GoalGetter, you agree to be bound by these Terms of Service. Please read them carefully before using our application.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          GoalGetter is a mobile application that uses AI to generate step-by-step plans from user-submitted goals. The service is available on both iOS and Android platforms.
        </p>

        <h2>3. User Responsibilities</h2>
        <p>
          To use GoalGetter, you must be 13 years of age or older. You are responsible for keeping your account credentials secure. You agree that you will not use the service to generate harmful, misleading, or illegal content.
        </p>

        <h2>4. Free and Pro Plans</h2>
        <p>GoalGetter offers two tiers of service:</p>
        <ul>
          <li><strong>Free Plan:</strong> Includes a limited number of plan generations per month.</li>
          <li><strong>Pro Subscription:</strong> Includes unlimited plans, custom themes, custom app icons, and priority features.</li>
        </ul>
        <p>Features included in both plans may change over time, and we will provide reasonable notice of material changes.</p>

        <h2>5. Subscription Terms</h2>
        <p>
          Pro is billed either monthly or annually via in-app purchase through the Apple App Store or Google Play. Your subscription will renew automatically unless cancelled at least 24 hours before the renewal date.
        </p>
        <p>
          The subscription price is displayed at checkout and may be subject to change with a 30-day notice. If a free trial period is offered, you will not be charged until the trial period concludes.
        </p>

        <h2>6. Cancellation and Refunds</h2>
        <p>
          You may cancel your subscription at any time through your device's App Store or Google Play subscription settings. Cancellation takes effect at the end of your current billing period.
        </p>
        <p>
          Because payments are processed by Apple and Google, refunds are subject entirely to the Apple App Store or Google Play refund policies. GoalGetter cannot and does not issue refunds directly.
        </p>

        <h2>7. AI-Generated Content</h2>
        <p>
          Plans within GoalGetter are generated by artificial intelligence. They may not always be accurate, complete, or suitable for your specific situation. GoalGetter makes no warranty or guarantee about the reliability of AI-generated content.
        </p>
        <p>
          <strong>Important:</strong> Do not substitute AI-generated plans for professional medical, legal, financial, or psychological advice.
        </p>

        <h2>8. Pro Feature Entitlements</h2>
        <p>
          Access to Pro features (such as custom themes and icons) is available only during an active subscription period. If your subscription is cancelled or expires, the app will automatically revert to the free default features.
        </p>

        <h2>9. Termination</h2>
        <p>
          You may delete your account and terminate your agreement with us at any time from the app's Profile screen. GoalGetter reserves the right to suspend or terminate accounts that violate these terms, with or without prior notice.
        </p>

        <h2>10. Limitation of Liability</h2>
        <p>
          GoalGetter is provided on an "as is" and "as available" basis without any warranty of any kind. To the maximum extent permitted by applicable law, we are not liable for any direct, indirect, incidental, or consequential damages arising from your use of the service.
        </p>

        <h2>11. Governing Law</h2>
        <p>
          These Terms of Service are governed by and construed in accordance with the laws of the United States.
        </p>

        <h2>12. Contact</h2>
        <p>
          If you have any questions or concerns about these Terms, please contact us at:<br/>
          <a href="mailto:legal@goalgetter.app" className="font-medium text-primary">legal@goalgetter.app</a>
        </p>

        <hr className="my-12 border-border/50" />
        
        <div className="not-prose text-center">
          <p className="text-muted-foreground mb-4">Learn how we protect your data.</p>
          <Link href="/privacy" className="inline-flex items-center gap-2 text-primary hover:text-primary/80 font-medium transition-colors">
            Read the Privacy Policy <span aria-hidden="true">&rarr;</span>
          </Link>
        </div>
      </article>
    </Layout>
  );
}
